builds:
  - env:
      - CGO_ENABLED=0
    goos: 
      - windows
      - linux
      - darwin
archive:
  replacements:
    darwin: macOS 
  format_overrides:
    - goos: windows
      format: zip
  wrap_in_directory: true
