
builds: 
  -
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=1
archive:
  replacements:
    darwin: macOS
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE 
    - gtfs.db
    - rebuild_gtfs_db.sh
checksum:
  name_template: 'checksums.txt'
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
